### ISSUE TITLE
Directions in kafka repo for auth aren't working

### ISSUE THREAD

**Issue by jeeftor** [bitnami/bitnami-docker-zookeeper#32]
**Description**

I'm trying to setup a SASL kafka as per the readme in the [kafka container](https://github.com/bitnami/bitnami-docker-kafka#security) and I'm running into issues

**Steps to reproduce the issue:**
`docker-compose.zk.yml`

```
version: "2"

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=kafka_password
```

`docker-compose -f docker-compose.zk.yml up`

**Describe the results you received:**

I get into a reboot loop of sorts:

```
zookeeper_1  | WATCHER::
zookeeper_1  |
zookeeper_1  | WatchedEvent state:SyncConnected type:None path:null
zookeeper_1  | 2020-05-28 21:00:09,105 [myid:localhost:2181] - WARN  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1272] - Session 0x1000391d1480001 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
zookeeper_1  | java.lang.IllegalArgumentException
zookeeper_1  | 	at java.base/javax.security.auth.callback.NameCallback.<init>(NameCallback.java:87)
zookeeper_1  | 	at java.security.sasl/com.sun.security.sasl.digest.DigestMD5Client.processChallenge(DigestMD5Client.java:326)
zookeeper_1  | 	at java.security.sasl/com.sun.security.sasl.digest.DigestMD5Client.evaluateChallenge(DigestMD5Client.java:220)
zookeeper_1  | 	at org.apache.zookeeper.client.ZooKeeperSaslClient$1.run(ZooKeeperSaslClient.java:320)
zookeeper_1  | 	at org.apache.zookeeper.client.ZooKeeperSaslClient$1.run(ZooKeeperSaslClient.java:317)
zookeeper_1  | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
zookeeper_1  | 	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
zookeeper_1  | 	at org.apache.zookeeper.client.ZooKeeperSaslClient.createSaslToken(ZooKeeperSaslClient.java:317)
zookeeper_1  | 	at org.apache.zookeeper.client.ZooKeeperSaslClient.respondToServer(ZooKeeperSaslClient.java:270)
zookeeper_1  | 	at org.apache.zookeeper.ClientCnxn$SendThread.readResponse(ClientCnxn.java:918)
zookeeper_1  | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:96)
zookeeper_1  | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:348)
zookeeper_1  | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1262)
zookeeper_1  |
zookeeper_1  | WATCHER::
zookeeper_1  |
zookeeper_1  | WatchedEvent state:Disconnected type:None path:null
zookeeper_1  | KeeperErrorCode = ConnectionLoss for /
zookeeper_1  | 2020-05-28 21:00:09,230 [myid:] - ERROR [main:ServiceUtils@42] - Exiting JVM with code 1
zookeeper_1  | /opt/bitnami/java/bin/java
zookeeper_1  | Connecting to localhost:2181
zookeeper_1  | 2020-05-28 21:00:14,741 [myid:] - INFO  [main:Environment@98] - Client environment:zookeeper.version=3.6.1--104dcb3e3fb464b30c5186d229e00af9f332524b, built on 04/21/2020 15:01 GMT
zookeeper_1  | 2020-05-28 21:00:14,747 [myid:] - INFO  [main:Environment@98] - Client environment:host.name=zookeeper
zookeeper_1  | 2020-05-28 21:00:14,747 [myid:] - INFO  [main:Environment@98] - Client environment:java.version=11.0.7
zookeeper_1  | 2020-05-28 21:00:14,752 [myid:] - INFO  [main:Environment@98] - Client environment:java.vendor=BellSoft
zookeeper_1  | 2020-05-28 21:00:14,752 [myid:] - INFO  [main:Environment@98] - Client environment:java.home=/opt/bitnami/java
zookeeper_1  | 2020-05-28 21:00:14,752 [myid:] - INFO  [main:Environment@98] - Client environment:java.class.path=/opt/bitnami/zookeeper/bin/../zookeeper-server/target/classes:/opt/bitnami/zookeeper/bin/../build/classes:/opt/bitnami/zookeeper/bin/../zookeeper-server/target/lib/*.jar:/opt/bitnami/zookeeper/bin/../build/lib/*.jar:/opt/bitnami/zookeeper/bin/../lib/zookeeper-prometheus-metrics-3.6.1.jar:/opt/bitnami/zookeeper/bin/../lib/zookeeper-jute-3.6.1.jar:/opt/bitnami/zookeeper/bin/../lib/zookeeper-3.6.1.jar:/opt/bitnami/zookeeper/bin/../lib/snappy-java-1.1.7.jar:/opt/bitnami/zookeeper/bin/../lib/slf4j-log4j12-1.7.25.jar:/opt/bitnami/zookeeper/bin/../lib/slf4j-api-1.7.25.jar:/opt/bitnami/zookeeper/bin/../lib/simpleclient_servlet-0.6.0.jar:/opt/bitnami/zookeeper/bin/../lib/simpleclient_hotspot-0.6.0.jar:/opt/bitnami/zookeeper/bin/../lib/simpleclient_common-0.6.0.jar:/opt/bitnami/zookeeper/bin/../lib/simpleclient-0.6.0.jar:/opt/bitnami/zookeeper/bin/../lib/netty-transport-native-unix-common-4.1.48.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-transport-native-epoll-4.1.48.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-transport-4.1.48.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-resolver-4.1.48.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-handler-4.1.48.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-common-4.1.48.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-codec-4.1.48.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-buffer-4.1.48.Final.jar:/opt/bitnami/zookeeper/bin/../lib/metrics-core-3.2.5.jar:/opt/bitnami/zookeeper/bin/../lib/log4j-1.2.17.jar:/opt/bitnami/zookeeper/bin/../lib/json-simple-1.1.1.jar:/opt/bitnami/zookeeper/bin/../lib/jline-2.11.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-util-9.4.24.v20191120.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-servlet-9.4.24.v20191120.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-server-9.4.24.v20191120.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-security-9.4.24.v20191120.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-io-9.4.24.v20191120.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-http-9.4.24.v20191120.jar:/opt/bitnami/zookeeper/bin/../lib/javax.servlet-api-3.1.0.jar:/opt/bitnami/zookeeper/bin/../lib/jackson-databind-2.10.3.jar:/opt/bitnami/zookeeper/bin/../lib/jackson-core-2.10.3.jar:/opt/bitnami/zookeeper/bin/../lib/jackson-annotations-2.10.3.jar:/opt/bitnami/zookeeper/bin/../lib/commons-lang-2.6.jar:/opt/bitnami/zookeeper/bin/../lib/commons-cli-1.2.jar:/opt/bitnami/zookeeper/bin/../lib/audience-annotations-0.5.0.jar:/opt/bitnami/zookeeper/bin/../zookeeper-*.jar:/opt/bitnami/zookeeper/bin/../zookeeper-server/src/main/resources/lib/*.jar:/opt/bitnami/zookeeper/bin/../conf:
zookeeper_1  | 2020-05-28 21:00:14,752 [myid:] - INFO  [main:Environment@98] - Client environment:java.library.path=/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
zookeeper_1  | 2020-05-28 21:00:14,753 [myid:] - INFO  [main:Environment@98] - Client environment:java.io.tmpdir=/tmp
zookeeper_1  | 2020-05-28 21:00:14,753 [myid:] - INFO  [main:Environment@98] - Client environment:java.compiler=<NA>
zookeeper_1  | 2020-05-28 21:00:14,753 [myid:] - INFO  [main:Environment@98] - Client environment:os.name=Linux
zookeeper_1  | 2020-05-28 21:00:14,753 [myid:] - INFO  [main:Environment@98] - Client environment:os.arch=amd64
zookeeper_1  | 2020-05-28 21:00:14,754 [myid:] - INFO  [main:Environment@98] - Client environment:os.version=4.19.76-linuxkit
zookeeper_1  | 2020-05-28 21:00:14,754 [myid:] - INFO  [main:Environment@98] - Client environment:user.name=?
zookeeper_1  | 2020-05-28 21:00:14,754 [myid:] - INFO  [main:Environment@98] - Client environment:user.home=?
zookeeper_1  | 2020-05-28 21:00:14,754 [myid:] - INFO  [main:Environment@98] - Client environment:user.dir=/
zookeeper_1  | 2020-05-28 21:00:14,755 [myid:] - INFO  [main:Environment@98] - Client environment:os.memory.free=1016MB
zookeeper_1  | 2020-05-28 21:00:14,758 [myid:] - INFO  [main:Environment@98] - Client environment:os.memory.max=1024MB
zookeeper_1  | 2020-05-28 21:00:14,758 [myid:] - INFO  [main:Environment@98] - Client environment:os.memory.total=1024MB
zookeeper_1  | 2020-05-28 21:00:14,766 [myid:] - INFO  [main:ZooKeeper@1005] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=org.apache.zookeeper.ZooKeeperMain$MyWatcher@646be2c3
zookeeper_1  | 2020-05-28 21:00:14,772 [myid:] - INFO  [main:X509Util@77] - Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
zookeeper_1  | 2020-05-28 21:00:14,790 [myid:] - INFO  [main:ClientCnxnSocket@239] - jute.maxbuffer value is 1048575 Bytes
zookeeper_1  | 2020-05-28 21:00:14,802 [myid:] - INFO  [main:ClientCnxn@1703] - zookeeper.request.timeout value is 0. feature enabled=false
zookeeper_1  | 2020-05-28 21:00:14,925 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):Login@320] - Client successfully logged in.
zookeeper_1  | 2020-05-28 21:00:14,930 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):SecurityUtils@70] - Client will use DIGEST-MD5 as SASL mechanism.
zookeeper_1  | 2020-05-28 21:00:15,005 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1154] - Opening socket connection to server localhost/127.0.0.1:2181.
zookeeper_1  | 2020-05-28 21:00:15,005 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1156] - SASL config status: Will attempt to SASL-authenticate using Login Context section 'Client'
zookeeper_1  | 2020-05-28 21:00:15,027 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@986] - Socket connection established, initiating session, client: /127.0.0.1:44092, server: localhost/127.0.0.1:2181
zookeeper_1  | 2020-05-28 21:00:15,039 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1420] - Session establishment complete on server localhost/127.0.0.1:2181, session id = 0x1000391d1480002, negotiated timeout = 30000
zookeeper_1  |
zookeeper_1  | WATCHER::
zookeeper_1  |
zookeeper_1  | WatchedEvent state:SyncConnected type:None path:null
zookeeper_1  | 2020-05-28 21:00:15,054 [myid:localhost:2181] - WARN  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1272] - Session 0x1000391d1480002 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
zookeeper_1  | java.lang.IllegalArgumentException
zookeeper_1  | 	at java.base/javax.security.auth.callback.NameCallback.<init>(NameCallback.java:87)
zookeeper_1  | 	at java.security.sasl/com.sun.security.sasl.digest.DigestMD5Client.processChallenge(DigestMD5Client.java:326)
zookeeper_1  | 	at java.security.sasl/com.sun.security.sasl.digest.DigestMD5Client.evaluateChallenge(DigestMD5Client.java:220)
zookeeper_1  | 	at org.apache.zookeeper.client.ZooKeeperSaslClient$1.run(ZooKeeperSaslClient.java:320)
zookeeper_1  | 	at org.apache.zookeeper.client.ZooKeeperSaslClient$1.run(ZooKeeperSaslClient.java:317)
zookeeper_1  | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
zookeeper_1  | 	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
zookeeper_1  | 	at org.apache.zookeeper.client.ZooKeeperSaslClient.createSaslToken(ZooKeeperSaslClient.java:317)
zookeeper_1  | 	at org.apache.zookeeper.client.ZooKeeperSaslClient.respondToServer(ZooKeeperSaslClient.java:270)
zookeeper_1  | 	at org.apache.zookeeper.ClientCnxn$SendThread.readResponse(ClientCnxn.java:918)
zookeeper_1  | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:96)
zookeeper_1  | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:348)
zookeeper_1  | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1262)
zookeeper_1  |
zookeeper_1  | WATCHER::
zookeeper_1  |
zookeeper_1  | WatchedEvent state:Disconnected type:None path:null
zookeeper_1  | KeeperErrorCode = ConnectionLoss for /
zookeeper_1  | 2020-05-28 21:00:15,179 [myid:] - ERROR [main:ServiceUtils@42] - Exiting JVM with code 1
^[zookeeper_1  | /opt/bitnami/java/bin/java
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)
  mutagen: Synchronize files with Docker Desktop (Docker Inc., testing)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 47
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 11.7GiB
 Name: docker-desktop
 ID: TO57:HH7O:UL62:B32Q:TQQH:UGWO:ZKSC:3MAQ:A7WJ:XW6D:ZTUP:M6LL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  mdc2-registry.mitre.org:9080
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment]
Hi @jeeftor 

I'm missing how you're configuring Kafka from the Docker Compose you shared. Did you set the `KAFKA_ZOOKEEPER_USER` and `KAFKA_ZOOKEEPER_PASSWORD` environment variables?

That said, we are working on some major changes that will change the way to configure authentication in Kafka. Please stay tuned to the [Notable Changes section](https://github.com/bitnami/bitnami-docker-kafka#notable-changes) of Kafka.
