### ISSUE TITLE
Zookeeper container needs to restart to work

### ISSUE THREAD

**Issue by FranciscoNC** [bitnami/bitnami-docker-zookeeper#36]
```
2020-06-11 17:50:04,969 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):Login@320] - Client successfully logged in.
2020-06-11 17:50:04,978 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):SecurityUtils@70] - Client will use DIGEST-MD5 as SASL mechanism.
2020-06-11 17:50:05,059 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1154] - Opening socket connection to server localhost/127.0.0.1:2181.
2020-06-11 17:50:05,059 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1156] - SASL config status: Will attempt to SASL-authenticate using Login Context section 'Client'
2020-06-11 17:50:05,074 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@986] - Socket connection established, initiating session, client: /127.0.0.1:59504, server: localhost/127.0.0.1:2181
2020-06-11 17:50:05,082 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1420] - Session establishment complete on server localhost/127.0.0.1:2181, session id = 0x1000020c1d8001c, negotiated timeout = 30000

WATCHER::

WatchedEvent state:SyncConnected type:None path:null
2020-06-11 17:50:05,092 [myid:localhost:2181] - WARN  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1272] - Session 0x1000020c1d8001c for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
java.lang.IllegalArgumentException
	at java.base/javax.security.auth.callback.NameCallback.<init>(NameCallback.java:87)
	at java.security.sasl/com.sun.security.sasl.digest.DigestMD5Client.processChallenge(DigestMD5Client.java:326)
	at java.security.sasl/com.sun.security.sasl.digest.DigestMD5Client.evaluateChallenge(DigestMD5Client.java:220)
	at org.apache.zookeeper.client.ZooKeeperSaslClient$1.run(ZooKeeperSaslClient.java:320)
	at org.apache.zookeeper.client.ZooKeeperSaslClient$1.run(ZooKeeperSaslClient.java:317)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
	at org.apache.zookeeper.client.ZooKeeperSaslClient.createSaslToken(ZooKeeperSaslClient.java:317)
	at org.apache.zookeeper.client.ZooKeeperSaslClient.respondToServer(ZooKeeperSaslClient.java:270)
	at org.apache.zookeeper.ClientCnxn$SendThread.readResponse(ClientCnxn.java:918)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:96)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:348)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1262)


```

**Description**

Hi, I'm trying to run a zookeeper container but I get this error. It shows this error until container shut down, I found that if I restart container, it will work normally after restart, but I'd like to avoid this step. Is there a solution?

**Steps to reproduce the issue:**

1. Run container
```
docker run -d --name zookeeper-test \
--network test-network \
-e ZOO_ENABLE_AUTH=yes \
-e ZOO_SERVER_USERS=test-zoo \
-e ZOO_SERVER_PASSWORDS=test-zoo \
bitnami/zookeeper
```
2. Watch logs
```
docker logs zookeeper-test -f
```
3. Wait to shut down

**Describe the results you received:**

Zookeeper container shuts down after a lot error logs

**Version**

- Output of `docker version`:
```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:22 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:10:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by FranciscoNC** [comment]
I found the solution, sorry

**Comment by mikebobadilla** [comment]
@FranciscoNC what was the solution?

**Comment by FranciscoNC** [comment]
This command was wrong

`
docker run -d --name zookeeper-test \
--network test-network \
-e ZOO_ENABLE_AUTH=yes \
-e ZOO_SERVER_USERS=test-zoo \
-e ZOO_SERVER_PASSWORDS=test-zoo \
bitnami/zookeeper
`
I have to set these environment variables:
`
ZOO_CLIENT_USER: User that will use ZooKeeper clients to auth. Default: No defaults.
ZOO_CLIENT_PASSWORD: Password that will use ZooKeeper clients to auth. No defaults.
`

**Comment by FranciscoNC** [comment]
Something like this
```
docker run -d --name zookeeper-test \
--network test-network \
-e ZOO_ENABLE_AUTH=yes \
-e ZOO_SERVER_USERS=test-zoo \
-e ZOO_SERVER_PASSWORDS=test-zoo \
-e ZOO_CLIENT_USER=test-zoo \
-e ZOO_CLIENT_PASSWORD=test-zoo \
bitnami/zookeeper
```

**Comment by zSakuraEvilz** [comment]
I also met the situation above.
I tried @FranciscoNC's solution.
But it is not resolved.
Pls, help me.

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue. I launched the container like this

```
docker run -d --name zookeeper-test \
--network test-network \
-e ZOO_ENABLE_AUTH=yes \
-e ZOO_SERVER_USERS=test-zoo \
-e ZOO_SERVER_PASSWORDS=test-zoo \
-e ZOO_CLIENT_USER=test-zoo \
-e ZOO_CLIENT_PASSWORD=test-zoo \
bitnami/zookeeper

```

And I could access without issues

```
[zk: localhost:2181(CONNECTED) 6] create test
Path must start with / character
[zk: localhost:2181(CONNECTED) 7] create /test
Created /test
[zk: localhost:2181(CONNECTED) 8] create /test/mk
Created /test/mk
[zk: localhost:2181(CONNECTED) 9] ls
ls [-s] [-w] [-R] path
[zk: localhost:2181(CONNECTED) 10] ls /
[test, zookeeper]
[zk: localhost:2181(CONNECTED) 11] ls /test
[mk]
```

**Comment by zSakuraEvilz** [comment]
Hi,
Thanks for the reply
I used it with docker-composer and got an error.

```yml
version: '3.7'

services:

  zookeeper:
    image: bitnami/zookeeper:3.6.2
    container_name: zookeeper_service
    restart: always
    ports:
      - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=test-zoo-server
      - ZOO_SERVER_PASSWORDS=test-zoo
      - ZOO_CLIENT_USER=test-zoo-client
      - ZOO_CLIENT_PASSWORD=test-zoo 
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
```
Run: 
```
docker-compose up
```
There will be an error on the first run.
```
Welcome to ZooKeeper!
JLine support is enabled
2020-10-13 12:09:02,657 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):Login@320] - Client successfully logged in.
2020-10-13 12:09:02,661 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):SecurityUtils@70] - Client will use DIGEST-MD5 as SASL mechanism.
[zk: localhost:2181(CONNECTING) 0] 2020-10-13 12:09:02,707 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1167] - Opening socket connection to server localhost/127.0.0.1:2181.
2020-10-13 12:09:02,709 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1169] - SASL config status: Will attempt to SASL-authenticate using Login Context section 'Client'
2020-10-13 12:09:02,716 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@999] - Socket connection established, initiating session, client: /127.0.0.1:36570, server: localhost/127.0.0.1:2181
2020-10-13 12:09:02,725 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1433] - Session establishment complete on server localhost/127.0.0.1:2181, session id = 0x10000f9fc990029, negotiated timeout = 30000

WATCHER::

WatchedEvent state:SyncConnected type:None path:null
2020-10-13 12:09:02,745 [myid:localhost:2181] - ERROR [main-SendThread(localhost:2181):ZooKeeperSaslClient@275] - SASL authentication failed using login context 'Client'.
javax.security.sasl.SaslException: Error in authenticating with a Zookeeper Quorum member: the quorum member's saslToken is null.
        at org.apache.zookeeper.client.ZooKeeperSaslClient.createSaslToken(ZooKeeperSaslClient.java:310)
        at org.apache.zookeeper.client.ZooKeeperSaslClient.respondToServer(ZooKeeperSaslClient.java:270)
        at org.apache.zookeeper.ClientCnxn$SendThread.readResponse(ClientCnxn.java:931)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:98)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1275)

WATCHER::

WatchedEvent state:AuthFailed type:None path:null
2020-10-13 12:09:02,746 [myid:localhost:2181] - WARN  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1285] - Session 0x10000f9fc990029 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
EndOfStreamException: Unable to read additional data from server sessionid 0x10000f9fc990029, likely server has closed socket
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1275)
2020-10-13 12:09:02,746 [myid:] - INFO  [main-EventThread:ClientCnxn$EventThread@577] - EventThread shut down for session: 0x10000f9fc990029

```
If I restart it then the error will be gone.
```
docker-compose restart
```

**Comment by javsalgar** [comment]
Ok, I just saw what happened. I believe we should improve the documentation. The `ZOO_CLIENT_USER` variable must be set with one of the users of the list `ZOO_SERVER_USERS`. Zookeeper will first create the users set in `ZOO_SERVER_USERS`, and then will use the client set ni `ZOO_CLIENT_USER`. Could you try again with an user set in `ZOO_SERVER_USERS`?

**Comment by zSakuraEvilz** [comment]
Hi

I tried with ZOO_CLIENT_USER variable is one of the users of the list ZOO_SERVER_USERS.
```yml
version: '3.7'

services:

  zookeeper:
    image: bitnami/zookeeper:3.6.2
    container_name: zookeeper_service
    restart: always
    ports:
      - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=test-zoo,test-zoo-client
      - ZOO_SERVER_PASSWORDS=test-zoo,test-zoo-client
      - ZOO_CLIENT_USER=test-zoo-client
      - ZOO_CLIENT_PASSWORD=test-zoo-client
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
```
It was able to run normally.
Thank you.

**Comment by javsalgar** [comment]
Thanks for letting us know!
