### ISSUE TITLE
Exit JVM with code 1

### ISSUE THREAD

**Issue by rmGFW** [bitnami/bitnami-docker-zookeeper#62]
**Description**

can't start zookeeper

**Steps to reproduce the issue:**

write compose and run docker-compose up 

**Describe the results you received:**
```
exit JVM with code 1
WATCHER::

WatchedEvent state:SyncConnected type:None path:null
2021-10-05 01:52:53,540 [myid:localhost:2181] - WARN  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1290] - Session 0x1009ae0701b0008 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
java.lang.IllegalArgumentException
        at java.base/javax.security.auth.callback.NameCallback.<init>(NameCallback.java:87)
        at java.security.sasl/com.sun.security.sasl.digest.DigestMD5Client.processChallenge(DigestMD5Client.java:326)
        at java.security.sasl/com.sun.security.sasl.digest.DigestMD5Client.evaluateChallenge(DigestMD5Client.java:220)
        at org.apache.zookeeper.client.ZooKeeperSaslClient$1.run(ZooKeeperSaslClient.java:320)
        at org.apache.zookeeper.client.ZooKeeperSaslClient$1.run(ZooKeeperSaslClient.java:317)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
        at org.apache.zookeeper.client.ZooKeeperSaslClient.createSaslToken(ZooKeeperSaslClient.java:317)
        at org.apache.zookeeper.client.ZooKeeperSaslClient.respondToServer(ZooKeeperSaslClient.java:270)
        at org.apache.zookeeper.ClientCnxn$SendThread.readResponse(ClientCnxn.java:928)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:98)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1280)

WATCHER::

WatchedEvent state:Disconnected type:None path:null
KeeperErrorCode = ConnectionLoss for /
2021-10-05 01:52:53,658 [myid:] - ERROR [main:ServiceUtils@42] - Exiting JVM with code 1
```
**Describe the results you expected:**
...

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu1~20.04.1
 Built:             Wed Aug  4 22:52:25 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```
Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu1~20.04.1
  Built:            Wed Aug  4 19:07:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.2-0ubuntu1~20.04.2
  GitCommit:        
 runc:
  Version:          1.0.0~rc95-0ubuntu1~20.04.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 41
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-77-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.843GiB
 Name: VM-8-16-ubuntu
 ID: BKGF:SBAO:2EAT:CBYG:AVPE:AMSJ:5ND2:SFWL:Q5PG:Z4OK:QZKI:DD4T
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

compoose info 

```

version: "3"

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    # ports:
    #   - "2181:2181"
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=kafka_PASSWORD
    networks:
      - app-tier

 
```

**Comment by miguelaeh** [comment]
Hi @rmGFW ,
Please add a description to the issue explaining what is happening and what are you trying to achieve, as well as your environment

**Comment by miguelaeh** [comment]
Hi @rmGFW ,
We are sorry, we missed this ticket.
It seems you are missing the following two wnv vars:
```
      - ZOO_CLIENT_USER=kafka
      - ZOO_CLIENT_PASSWORD=kafka
```

The following docker-compose should work for you:
```
version: "3"

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_CLIENT_USER=kafka
      - ZOO_CLIENT_PASSWORD=kafka
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=kafka
    networks:
      - app-tier
      - ```
